### ISSUE TITLE
关于运行onelink测试时 Connection Refused

### ISSUE THREAD

**Issue by ShaokangXie** [Nancyzxy/CS305-proj#18]
![HHYGZN78PY7CR32D1ONIKSQ](https://user-images.githubusercontent.com/75991596/171148979-a0910683-23aa-417b-9730-debce79b4678.png)

当运行 ```python3 netsim.py onelink run -e topology/onelink/onelink.events``` 报Connection Refused错误，请问该如何解决

**Comment by Yhcrown** [comment]
请先关闭原先开启的服务器并执行：
python3 netsim.py onelink start

**Comment by ShaokangXie** [comment]
解决了，非常感谢！
