### ISSUE TITLE
apache的动态链接库问题

### ISSUE THREAD

**Issue by Fros1er** [Nancyzxy/CS305-proj#3]
rt，apache的动态链接好像全炸了。。。
暂时这么修了一下，要不netsim跑不起来
``` bash
apt install libapr1 # 不知道需不需要
chmod +x /usr/local/apache2/bin/httpd
cd /usr/local/apache2/lib/
rm libaprutil-1.so.0
ln -s libaprutil-1.so.0.5.3 libaprutil-1.so.0
rm libexpat.so.0
ln -s libexpat.so.0.5.0 libexpat.so.0
rm libapr-1.so.0
ln -s libapr-1.so.0.5.1 libapr-1.so.0
```

---
更新：我在自己的repo里加上了。。。
不过顺手装了个fish，所以不太适合合到这里面了
https://github.com/Fros1er/CS305-proj/blob/main/docker_setup/DockerFile

**Comment by XinyingZheng00** [comment]
确实有这个问题，之前我的电脑也遇到了，不过有个用mac的SA没出现，所以我以为是我电脑的缘故，好像原因就是真正的文件在.0.5.0里面，但是他每次都会找.0 所以你这样应该就可以解决。第一句应该不需要。

**Comment by zly7** [comment]
通过docker cp 拷贝clone到本地的文件也是可以的

**Comment by Leo-Adventure** [comment]
感谢

**Comment by SpaceIshtar** [comment]
感谢
