### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by xyllq999** [Nancyzxy/CS305-proj#7]
请问一下build image的命令是在哪里运行呢？在本机终端吗还是先在docker新建环境再运行

**Comment by XinyingZheng00** [comment]
在本机终端运行 建立一个docker 镜像，然后进入镜像进行开发

**Comment by xyllq999** [comment]
但是话说mac会报错怎么办捏报错permission denied

**Comment by XinyingZheng00** [comment]
你把sudo去掉build试试

**Comment by xyllq999** [comment]
去掉不让跑捏1.unknown shorthand flag: 't' in -t   2.unknown shorthand flag: 'f' in -f

**Comment by FhToday** [comment]
`cd /docker_setup`
`sudo docker build -t project:latest -f ./DockerFile .`
请提供terminal运行的完整截图，没有遇到过这个问题。

**Comment by xyllq999** [comment]
现在通过更改权限跑通了，但是在m1的mac上会出现闪退，还会有amd的warning。

**Comment by FhToday** [comment]
我在m1没有遇到这种问题。
请你提供详细的warning信息，没有的话可以查日志文件，闪退和warning这样的问题太宽泛，没办法帮到你。

**Comment by xyllq999** [comment]
请问一下我的vscode的连接docker后的工作区中，home文件夹下找不到project的文件怎么操作呢，如
<img width="562" alt="截屏2022-05-04 17 45 14" src="https://user-images.githubusercontent.com/72729433/166659045-0641d6e7-b8a5-4f0d-af39-649df22413c0.png">
图

**Comment by xyllq999** [comment]
直接复制过来吗？

**Comment by XinyingZheng00** [comment]
把本目录的文件拖进去哦

**Comment by xyllq999** [comment]
原来如此我以为自带有，感谢
