### ISSUE TITLE
关于dns server和throughput的问题

### ISSUE THREAD

**Issue by Fros1er** [Nancyzxy/CS305-proj#9]
1. project里的DNS Server需要是一个单独的server吗....能否直接集成到proxy里
2. 文档中提到`To calculate the throughput for a particular chunk, you should note the start time ts of the
request and the end time tf we you finished receiving the chunk from the server`。这里的request是指的client到proxy的请求还是proxy到server的请求，还是两者都有？

**Comment by XinyingZheng00** [comment]
1 不要集成 写成两个文件
2 直接记录proxy到server就可

**Comment by Fros1er** [comment]
> 1 不要集成 写成两个文件 

我的意思是，需要通过网络交互吗...

**Comment by XinyingZheng00** [comment]
需要

**Comment by Fros1er** [comment]
还有一个问题...
`suppose B is the length of the video chunk`
这里的length指的是文件大小还是bitrate
还有, ts和tf的单位是什么(

**Comment by XinyingZheng00** [comment]
是

**Comment by Fros1er** [comment]
> 是

所以是什么(

**Comment by XinyingZheng00** [comment]
length是文件大小
ts tf单位是秒

**Comment by Fros1er** [comment]
> length是文件大小 ts tf单位是秒

文件大小是kb...?

**Comment by XinyingZheng00** [comment]
byte
